import React from 'react';
import { Link } from 'react-router-dom';
import styles from './Dashboard.module.css';

const Dashboard = () => {
  const languages = [
    { 
      name: 'C', 
      icon: '🔧', 
      description: 'Master system programming and embedded systems',
      color: '#A8B9CC',
      difficulty: 'Beginner',
      topics: 4,
      timeToComplete: '2-3 weeks'
    },
    { 
      name: 'C++', 
      icon: '⚡', 
      description: 'Build high-performance applications and games',
      color: '#1565C0',
      difficulty: 'Intermediate',
      topics: 5,
      timeToComplete: '3-4 weeks'
    },
    { 
      name: 'C#', 
      icon: '🎯', 
      description: 'Create modern applications and web services',
      color: '#7B1FA2',
      difficulty: 'Intermediate',
      topics: 4,
      timeToComplete: '2-3 weeks'
    },
    { 
      name: 'Java', 
      icon: '☕', 
      description: 'Develop enterprise apps and Android applications',
      color: '#F57C00',
      difficulty: 'Beginner',
      topics: 5,
      timeToComplete: '3-4 weeks'
    },
    { 
      name: 'Python', 
      icon: '🐍', 
      description: 'Explore data science, AI, and web development',
      color: '#388E3C',
      difficulty: 'Beginner',
      topics: 4,
      timeToComplete: '2-3 weeks'
    }
  ];

  const getDifficultyColor = (difficulty) => {
    switch(difficulty) {
      case 'Beginner': return '#4CAF50';
      case 'Intermediate': return '#FF9800';
      case 'Advanced': return '#F44336';
      default: return '#9E9E9E';
    }
  };

  return (
    <div className={styles.dashboard}>
      <div className="page-container">
        <header className={styles.header}>
          <div className={styles.welcomeSection}>
            <h1 className={styles.mainTitle}>
              🎓 Welcome to <span className={styles.brandName}>Shikshak</span>! 
            </h1>
            <p className={styles.subtitle}>
              Your AI-powered programming mentor - Start learning, practicing, and mastering code today!
            </p>
            <div className={styles.statsRow}>
              <div className={styles.statItem}>
                <span className={styles.statNumber}>5</span>
                <span className={styles.statLabel}>Languages</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statNumber}>20+</span>
                <span className={styles.statLabel}>Topics</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statNumber}>∞</span>
                <span className={styles.statLabel}>Practice</span>
              </div>
            </div>
          </div>
        </header>

        <section className={styles.featuresSection}>
          <h2 className={styles.sectionTitle}>🚀 What Makes Shikshak Special?</h2>
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🤖</div>
              <h3>AI-Powered Learning</h3>
              <p>Get personalized tutorials generated by advanced AI</p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>⚡</div>
              <h3>Instant Code Execution</h3>
              <p>Run and test your code directly in the browser</p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🎯</div>
              <h3>Smart Quizzes</h3>
              <p>Challenge yourself with adaptive programming quizzes</p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>📚</div>
              <h3>No Barriers</h3>
              <p>Start learning immediately - no signup required!</p>
            </div>
          </div>
        </section>

        <section className={styles.languagesSection}>
          <h2 className={styles.sectionTitle}>💻 Choose Your Programming Journey</h2>
          <p className={styles.sectionSubtitle}>Select a language to begin your coding adventure</p>
          <div className={styles.languagesGrid}>
            {languages.map(language => {
              return (
                <div 
                  key={language.name} 
                  className={`${styles.languageCard} ${styles.enhancedCard}`}
                  style={{ '--accent-color': language.color }}
                >
                  <div className={styles.languageHeader}>
                    <div className={styles.languageIconLarge}>{language.icon}</div>
                    <div className={styles.languageInfo}>
                      <h3 className={styles.languageName}>{language.name}</h3>
                      <span 
                        className={styles.difficultyBadge}
                        style={{ backgroundColor: getDifficultyColor(language.difficulty) }}
                      >
                        {language.difficulty}
                      </span>
                    </div>
                  </div>
                  
                  <p className={styles.languageDescription}>
                    {language.description}
                  </p>

                  <div className={styles.languageStats}>
                    <div className={styles.statRow}>
                      <span className={styles.statIcon}>📖</span>
                      <span>{language.topics} Topics</span>
                    </div>
                    <div className={styles.statRow}>
                      <span className={styles.statIcon}>⏱️</span>
                      <span>{language.timeToComplete}</span>
                    </div>
                  </div>
                  
                  <div className={styles.languageActions}>
                    <Link 
                      to={`/tutor/${language.name}/Variables and Data Types`}
                      className={`${styles.primaryButton} ${styles.glowButton}`}
                    >
                      🚀 Start Learning
                    </Link>
                    
                    <Link 
                      to={`/custom-quiz/${language.name}`}
                      className={styles.secondaryButton}
                    >
                      🎯 Practice Quiz
                    </Link>
                  </div>

                  <div className={styles.cardGlow} style={{ backgroundColor: language.color }}></div>
                </div>
              );
            })}
          </div>
        </section>

        <section className={styles.ctaSection}>
          <div className={styles.ctaCard}>
            <h2>Ready to become a programming expert? 🌟</h2>
            <p>Join thousands of learners who are mastering programming with Shikshak's AI-powered platform</p>
            <div className={styles.ctaButtons}>
              <Link to="/tutor/Python/Variables and Data Types" className={styles.ctaPrimary}>
                🐍 Start with Python
              </Link>
              <Link to="/custom-quiz/Python" className={styles.ctaSecondary}>
                🎮 Take a Quick Quiz
              </Link>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Dashboard;
